### ISSUE TITLE
report error when start with zsh-users/zsh-history-substring-search

### ISSUE THREAD

**Issue by wweir** [zpm-zsh/zpm#15]
put `zpm load zsh-users/zsh-history-substring-search` into .zshrc

run `zsh`, it report:
/var/folders/ss/nftfg4t90cj6546f877r5rf40000gn/T//zsh-501/zpm-cache.zsh:source:1881: no such file or directory: /private/var/folders/ss/nftfg4t90cj6546f877r5rf40000gn/T/zsh-501/zsh-history-substring-search.zsh
<img width="974" alt="图片" src="https://user-images.githubusercontent.com/2841254/77877781-5297fd80-7289-11ea-8402-c5da504400ca.png">

**Comment by horosgrisa** [comment]
@wweir This error appears because `zsh-users/zsh-history-substring-search` doesn't support [$0 from zsh plugin standard](https://github.com/zdharma/Zsh-100-Commits-Club/blob/master/Zsh-Plugin-Standard.adoc#zero-handling)

You can source `zsh-history-substring-search.zsh` directly `zpm zsh-users/zsh-history-substring-search,source:zsh-history-substring-search.zsh,async`

Also, I recommend `async` tag, for faster loading

**Comment by wweir** [comment]
FYI
Maybe the sourced content can be wrapped in a function or some other scope.

**Comment by horosgrisa** [comment]
@wweir Why?

**Comment by wweir** [comment]
@horosgrisa Just like `zsh-history-substring-search`, nobody can make sure all plugins they need are compatible with `zpm`.
The cost of resolving compatibility issues is quite high.

**Comment by horosgrisa** [comment]
Do you think that wrapping will help?

**Comment by wweir** [comment]
I not sure if wrapping by a function will help, but the code sourced should be wrapped by something to reduce mutual interference

**Comment by horosgrisa** [comment]
@wweir I thought about this, but I don't want to add wrapping for efficiency and speed

**Comment by horosgrisa** [comment]
@wweir Now plugins will be wrapped into anonymous function. Check `next` branch.
